
# XML-bestand met playlist
playlisturl: http://www.zuidwesttv.nl/teksttv/playlist.xml

# XML-bestand met programmering
programmeringurl: http://www.zuidwesttv.nl/teksttv/fmprogrammering.php
  
# Fallback (tekst, image of tekstimage, nowonair)
fallback: nowonair

# Toon deze songtypes wel
songtypeshow: [1,2,3,4,5,6]

# Toon deze songtypes nooit
songtypehide:
  - 8
  - 9
  - 10
  - 13

# Vervang type door custom tekst of image (tekst, image of tekstimage)
songtypereplace:
  - replace: [20, 21, 22]
    text: 'ZuidWest FM Nieuws, weer en verkeer'
 - replace: [22]
    text: 'ZuidWest Verkeer - Powered by ANWB'
    image: 'http://localhost/anwbpromo.png'
    imagemode: cover
  - replace: [24]
    text: 'ZuidWest Update met Jos Geelhoed'
    image: 'http://localhost/hoofdfotojos.png'
  - replace: [23]
    image: http://localhost/commercials.png
    imagemode: fullscreen 

# Complete overrule (tekst, image of tekstimage, nowonair)
overrules:
  - overrule: 0
    image: http://localhost/commercials.png"
